### ISSUE TITLE
Cannot find module server.js

### ISSUE THREAD

**Issue by mikecoppola16** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#4]
I get error when I try to run npm start. Did I miss a step some how?

c:\work\angular\pricecompare1>npm start

> angular2-express@1.0.0 start c:\work\angular\pricecompare1
> concurrent --kill-others "gulp watch" "gulp start"

[1] [09:27:55]
[0] [09:27:55]
[1] Requiring external module ts-node/register
[0] Requiring external module ts-node/register
[1](node:3976) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[0](node:7136) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[1] [09:27:56]
[1] Using gulpfile c:\work\angular\pricecompare1\gulpfile.ts
[1] [09:27:56] Starting 'start'...
[1] [09:27:56]
[1] Finished 'start' after 1.82 ms
[1] [09:27:56] [nodemon] 1.10.0
[1] [09:27:56] [nodemon] to restart at any time, enter `rs`
[1] [09:27:56] [nodemon] watching: _._
[1] [09:27:56] [nodemon] starting `node dist/server/server.js`
[0] [09:27:56]
[0] Using gulpfile c:\work\angular\pricecompare1\gulpfile.ts
[0] [09:27:56]
[0] Starting 'watch'...
[0] [09:27:56]
[0] Finished 'watch' after 34 ms
[1] module.js:442
[1]     throw err;
[1]     ^
[1]
[1] Error: Cannot find module 'c:\work\angular\pricecompare1\dist\server\server.js'
[1]     at Function.Module._resolveFilename (module.js:440:15)
[1]     at Function.Module._load (module.js:388:25)
[1]     at Module.runMain (module.js:575:10)
[1]     at run (bootstrap_node.js:352:7)
[1]     at startup (bootstrap_node.js:144:9)
[1]     at bootstrap_node.js:467:3
[1] [09:27:57] [nodemon] app crashed - waiting for file changes before starting...

**Comment by moizKachwala** [comment]
can you check if your folder has dist folder ? can u rerun the commands npm install and then npm build

**Comment by moizKachwala** [comment]
fixed issues and updated to rc5
