### ISSUE TITLE
when I update the file, website doesn't work

### ISSUE THREAD

**Issue by anjia** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#42]
when i run these commands first time, everything goes well.
```
npm install
npm run build
npm run deploy
```

but, when I change the file `client/app/app.component.ts` like this: set the value of `title` property to 'Hello world', and save it. There are errors happened.

To solve this issue, how should I do? Thank you.

![image](https://user-images.githubusercontent.com/7055639/29161343-7166a600-7de8-11e7-9cf2-4c650c03527a.png)

-----
the content of `npm-debug.log` is as follows:
<pre>
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy' ]
2 info using npm@4.1.1
3 info using node@v7.4.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle angular2-express-mongo@1.0.0~predeploy: angular2-express-mongo@1.0.0
6 silly lifecycle angular2-express-mongo@1.0.0~predeploy: no script for predeploy, continuing
7 info lifecycle angular2-express-mongo@1.0.0~deploy: angular2-express-mongo@1.0.0
8 verbose lifecycle angular2-express-mongo@1.0.0~deploy: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-express-mongo@1.0.0~deploy: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/anjia/GitHub/master0810/node_modules/.bin:/usr/local/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
10 verbose lifecycle angular2-express-mongo@1.0.0~deploy: CWD: /Users/anjia/GitHub/master0810
11 silly lifecycle angular2-express-mongo@1.0.0~deploy: Args: [ '-c',
11 silly lifecycle   'concurrently --kill-others "gulp watch" "node ./dist/server/bin/www"' ]
12 silly lifecycle angular2-express-mongo@1.0.0~deploy: Returned: code: 1  signal: null
13 info lifecycle angular2-express-mongo@1.0.0~deploy: Failed to exec deploy script
14 verbose stack Error: angular2-express-mongo@1.0.0 deploy: `concurrently --kill-others "gulp watch" "node ./dist/server/bin/www"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-express-mongo@1.0.0
16 verbose cwd /Users/anjia/GitHub/master0810
17 error Darwin 15.6.0
18 error argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "deploy"
19 error node v7.4.0
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error angular2-express-mongo@1.0.0 deploy: `concurrently --kill-others "gulp watch" "node ./dist/server/bin/www"`
22 error Exit status 1
23 error Failed at the angular2-express-mongo@1.0.0 deploy script 'concurrently --kill-others "gulp watch" "node ./dist/server/bin/www"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-express-mongo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     concurrently --kill-others "gulp watch" "node ./dist/server/bin/www"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-express-mongo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-express-mongo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
</pre>

**Comment by anjia** [comment]
the changes do not go into effect immediately, I need to rebuild manually.

**Comment by mojtabaramezani** [comment]
You must make sure that you have installed the program.
You must check the nodeJS version and npm version.

**Comment by ghost** [comment]
You must make sure that you have installed the node_modules.
You must check the nodeJS version and npm version.

**Comment by facetrollex** [comment]
having the same issue
