### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by ghost** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#5]
I am getting build error.

I created dist folder even i am getting below error.

 Error: Cannot find module 'D:\Angularjs2\Angular2-expressjs-mongoose-
-node-typescript\dist\server\server.js'
     at Function.Module._resolveFilename (module.js:325:15)
     at Function.Module._load (module.js:276:25)
     at Function.Module.runMain (module.js:441:10)
     at startup (node.js:139:18)
     at node.js:968:3
 [14:39:31] [nodemon] app crashed - waiting for file changes before starting

**Comment by moizKachwala** [comment]
which version of node are you using ?
can you run the command, npm build and check if you get any errors. If you doesn't get any error then explore the folder and check if the command created any dist folder

**Comment by ghost** [comment]
4.4.7 I am Using.
npm build when i run with out taking much time command is getting out with no errors.
It didn't create any folder like dist. From my end i create folder dist and ran the server, but my bad.

**Comment by moizKachwala** [comment]
fixed issues and also updated angular to RC5

**Comment by esuarezz** [comment]
still this issue:

[12:48:25] Failed to load external module ts-node/register
[12:48:25] Failed to load external module typescript-node/register
[12:48:25] Failed to load external module typescript-register
[12:48:25] Failed to load external module typescript-require
